# a = int(input())
# print(str(a) + str(a + a) + str(a + a + a) + str(a + a + a + a))
a = input("Nhập số a: ")
n1 = int("%s" % a)
n2 = int("%s%s" % (a, a))
n3 = int("%s%s%s" % (a, a, a))
n4 = int("%s%s%s%s" % (a, a, a, a))
print(n1)
print(n2)
print(n3)
print(n4)
# Bài tập Python 18, Code by Quantrimang.com
print("Tổng cần tính là: ", n1 + n2 + n3 + n4)
print(1 + 11 + 111 + 1111)
